So this is notebook will showcase my work in matplotlib.

we will be dealing with data from kaggle name Titanic

https://www.kaggle.com/competitions/titanic/overview this will be data using this data is usually used in ML Prediction for my Scikit-Learn Repo i will be using this again

In [5]:
#Now Lets import lib needed for this project
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
#Lets Import the data
data = pd.read_csv('test.csv')
data.head() # will generate the first 5 rows of the data

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [9]:
#Lets have a look at the data
data.info() # will give us the info about the data
data.isnull().sum() # will give us the number of null values in each column

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [10]:
data.describe() # will give us the statistical summary of the data

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [11]:
data.shape # will give us the number of rows and columns in the data

(418, 11)

In [24]:
#Fill Age with mean
data['Age'] = data['Age'].fillna(data['Age'].mean())

#Fill Fare with median (safest for outliers)
data['Fare'] = data['Fare'].fillna(data['Fare'].median())

#Fill Cabin with '0' (convert to object first to ensure string type)
data['Cabin'] = data['Cabin'].astype('object').fillna('0')

In [25]:
#now have a look at the data again
data.info()
data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         418 non-null    float64
 9   Cabin        418 non-null    object
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), object(1), str(4)
memory usage: 36.1+ KB

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64